### ISSUE TITLE
Tags on GitHub

### ISSUE THREAD

**Issue by dotlambda** [ProtonVPN/python-proton-vpn-network-manager-openvpn#2]
Version 0.0.1 was released on PyPI: https://pypi.org/project/proton-vpn-network-manager-openvpn/#history
However it wasn't tagged on GitHub: https://github.com/ProtonVPN/python-proton-vpn-network-manager-openvpn/tags

**Comment by alexandrevicenzi** [comment]
@calexandru2018 can you fix the tags/releases in this project?

**Comment by calexandru2018** [comment]
Closing as all necessary tags have been released, thank you all.
Also don't rely on pypi, for now we won't be pushing packages there.
